### ISSUE TITLE
LED pulse on iPad not showing?

### ISSUE THREAD

**Issue by arrancurran** [madeslowly/slow-steps#11]

**Comment by tristancollins** [comment]
Same with Safari

**Comment by arrancurran** [comment]
The downside of developing in Chrome! They have already implemented SVG 2 which means we can style (and animate) svg elements with CSS. Firefox and Safari use SVG 1.1.

Now controlling animation within the svg markup. See https://stackoverflow.com/questions/32409101/resizing-svg-circle-radius-using-css-animation

**Comment by arrancurran** [comment]
confirmed - Safari 14.0.1, Firefox 84.0.2 iOS Safari 14
