### ISSUE TITLE
When changing the deploy URL and baseURL some addresses aren't generated correctly

### ISSUE THREAD

**Issue by tristancollins** [madeslowly/slow-steps#13]
e.g., I tried a test deploy (manually) to my VPS under one of my domains. 

`# Deploy url, if deploying to https://www.domain.com/foo just enter 'https://www
.domain.com here'
url:                       'https://www.tristancollins.me/'`

`# Deploy baseurl, if deploying to https://www.domain.com/foo just enter '/foo' h
ere, otherwise leave empty quotes
baseurl:                   'beta'`

`/beta` resulted in too many `\`'s in the html.

The css and various other things failed to load:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/8229525/105615390-3640f080-5dc8-11eb-8c94-f8e99d733265.png">

**Comment by tristancollins** [comment]
trying `/beta/` gives
![image](https://user-images.githubusercontent.com/8229525/105616478-19f48200-5dcf-11eb-8a73-6be07a8098b2.png)
 but also
![image](https://user-images.githubusercontent.com/8229525/105616488-32fd3300-5dcf-11eb-9ee9-270977152310.png)

**Comment by arrancurran** [comment]
Should be fixed now, https://www.gaitq.madeslowly.xyz/beta. Silly mistake on my part! I was hard coding site.baseurl into the links AND using a Jekyll filter `relative_url` which was adding a second `/beta`.

I'll leave open until you get the same result on your own server.

**Comment by tristancollins** [comment]
Works apart from the links on the main landing page?

**Comment by arrancurran** [comment]
Added relative_url to the buttons on landing page and also sitemap links in footer.

**Comment by arrancurran** [comment]
assuming this is all fixed your end and closing.
