### ISSUE TITLE
Add 'north', 'center', 'south' image options to Post entries

### ISSUE THREAD

**Issue by tristancollins** [madeslowly/slow-steps#18]
Thinking something like adding 

```---
layout:       post
categories:   [ news ] # Array of categories [ news, press, etc ]
title:        "Oxford BioDesign Winners"
subtitle:     "gaitQ's journey begins"
date:         2016-12-12 # YYYY - MM - DD First publish date, modified dates are automatically generated.
#author:       Joe-Blog
description:  gaitQ founding team wins Oxford Biodesign # Short description of this post
image:        gaitQ_Founders.jpg
image_alt:    The description of this image
image_focus:   NORTH CENTER SOUTH OPTIONS
env:          clinician
---
```

for the header image so it can be manually selected to look best.

And then adding the same option in the image-post.html file for the inserted images.

**Comment by tristancollins** [comment]
gah, only works if the image is being resized? Have given it a go adding 

`  {% picture post {{ include.link | prepend: 'posts/' }} {{include.focus}} --alt {{include.alt}} --img class="post__content--image" %}`

to image-post.html and

`{% picture {{ page.image | prepend: 'posts/' }} {{ page.image_focus }} --alt {{ page.image_alt }} --img class="post__hero" %}`

to post.html

**Comment by tristancollins** [comment]
Should this actually be done in CSS?

**Comment by tristancollins** [comment]
Yes. Yes it is. .post__content--image object-postion: top

**Comment by arrancurran** [comment]
Doing a bit of restructuring. So in Font Matter we'll refer to image as `hero` so as to avoid cross over with content images. In front matter `hero_focus` will control object-position and for content image add image--north or image--south to class. defaults to image--center.

**Comment by arrancurran** [comment]
OK get a fresh copy of both repos. In post front matter, you can control `object-position` with `hero_focus` `north` or `south`. Defaults to center so leave blank.

For post content images, add arg `focus="OPTION"`. Same as front matter, `north` or `south`.

**Comment by arrancurran** [comment]
example

`{% include image-post.html link="" alt="" caption="" focus="north" %}`

**Comment by tristancollins** [comment]
awesome!
