### ISSUE TITLE
About page role description fade doesn't render properly in Safari

### ISSUE THREAD

**Issue by tristancollins** [madeslowly/slow-steps#5]
![image](https://user-images.githubusercontent.com/8229525/102643555-5b05d080-4157-11eb-91a0-62c1f6edfcb2.png)

Fine in FireFox

![image](https://user-images.githubusercontent.com/8229525/102643613-6ce77380-4157-11eb-976d-e0d28158077c.png)

**Comment by arrancurran** [comment]
That's odd. The fade is achieved with linear-gradient( rgba(black, 0), white ). Changing to rgba(white, 0) seems to fix it.

Looks like a known thing in Sarafi when using rgba and the colour you fade to is not the same as the colour you fade from. 🤷‍♂️

https://ambientimpact.com/web/snippets/safari-bug-with-gradients-that-fade-to-transparent

**Comment by arrancurran** [comment]
OK just deployed and it's fixed.

<img width="999" alt="Screenshot 2020-12-19 at 13 20 32" src="https://user-images.githubusercontent.com/8464877/102690410-277d8180-41fd-11eb-8802-826918d765a3.png">
